workspace = { members = ["examples/demo"] }
[package]
name = "bad-tui"
version = "0.1.0"
edition = "2021"
autoexamples = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.27.0", features = ["events"] }
